sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:kzemek/boost
          packages:
            - g++-6
            - cmake
            - libboost-dev
      env:
        - TOOLCHAIN="export CC=gcc-6 CXX=g++-6"
        - CMAKE_CXX_FLAGS="-isystem=/usr/include/c++/6/"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ppa:kzemek/boost
          packages:
            - g++-7
            - cmake
            - libboost-dev
      env:
        - TOOLCHAIN="export CC=gcc-7 CXX=g++-7"
        - CMAKE_CXX_FLAGS="-isystem=/usr/include/c++/6/"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
            - ppa:kzemek/boost
          packages:
            - clang-5.0
            - libstdc++-6-dev
            - cmake
            - libboost-dev
      env:
        - TOOLCHAIN="export CC=clang-5.0 CXX=clang++-5.0"
        - CMAKE_CXX_FLAGS="-isystem=/usr/include/c++/6/"
        - CMAKE_LTO=OFF

before_install:
  - echo ${TOOLCHAIN} 
  - eval ${TOOLCHAIN}

script:
  - export SRCDIR="$(pwd)"
  - mkdir ../build/
  - cd ../build/
  - cmake "$SRCDIR" -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build .
  - ctest
