sudo: false
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libboost-dev
            - ninja
      env:
        - CC=gcc-6
        - CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - libboost-dev
            - ninja
      env:
        - CC=gcc-7
        - CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - cmake
            - libboost-dev
            - ninja
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0"

before_install:
  - echo "Matrix eval: ${CC} ${CXX}"

script:
  - export SRCDIR="$(pwd)"
  - echo "$SRCDIR"
  - mkdir ../build/
  - cd ../build/
  - cmake -G "Unix Makefiles" "$SRCDIR" && make && make test
