# This file mostly graciously borrowed from Lous Dionne, here:
# https://github.com/ldionne/dyno/blob/master/.travis.yml
# Distributed under the Apache 2.0 license (See LICENSE.txt file)
#
# Ideas for this travis file borrowed from Louis Dionne's .travis.yml files.

branches:
  except: /pr\/.*/

sudo: false
language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.64.0
 
matrix:
  include:
    - env: COMPILER=clang++-3.7
      addons: { apt: { packages: ["clang-3.7"], sources: ["llvm-toolchain-trusty-3.7", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-3.8
      addons: { apt: { packages: ["clang-3.8"], sources: ["llvm-toolchain-trusty-3.8", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-3.9
      addons: { apt: { packages: ["clang-3.9"], sources: ["llvm-toolchain-trusty-3.9", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=clang++-4.0
      addons: { apt: { packages: ["clang-4.0"], sources: ["llvm-toolchain-trusty-4.0", "ubuntu-toolchain-r-test"] } }

    - env: COMPILER=g++-6
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: COMPILER=g++-7
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode7.3

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode8

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode8.1

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode8.2

    - os: osx
      env: COMPILER=clang++
      osx_image: xcode8.3


install:
  # Set the ${CXX} variable properly
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version

  # Dependencies required by the CI are installed in ${TRAVIS_BUILD_DIR}/deps/
  - export SRCDIR="$(pwd)"
  - export DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - CMAKE_VERSION=3.8.0
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version

  # Install libc++ and libc++abi if needed
  - |
    if [[ "${CXX%%+*}" == "clang" ]]; then
      if   [[ "${CXX}" == "clang++-3.7" ]]; then LLVM_VERSION="3.7.1";
      elif [[ "${CXX}" == "clang++-3.8" ]]; then LLVM_VERSION="3.8.1";
      elif [[ "${CXX}" == "clang++-3.9" ]]; then LLVM_VERSION="3.9.1";
      elif [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION="4.0.0";
      fi

      LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
      LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
      LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"

      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
      travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
      travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
      (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/llvm/install)
      (cd llvm/build/projects/libcxx && make install -j2)
      (cd llvm/build/projects/libcxxabi && make install -j2)

      export CXXFLAGS="-isystem ${DEPS_DIR}/llvm/install/include/c++/v1"
      export LDFLAGS="-L ${DEPS_DIR}/llvm/install/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
    fi

  # Install Boost headers
  - BOOST_VERSION=1.64.0 # Keep this in sync with the cached directory
  - BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
  - |
    if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
      BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
      mkdir -p ${BOOST_DIR}
      { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
    fi

before_install:
  - echo ${TOOLCHAIN} 
  - eval ${TOOLCHAIN}

script:
  - cd "${SRCDIR}"
  - if [[ "${CXX%%+*}" == "clang" ]]; then export CMAKE_LTO=OFF; fi
  - mkdir ../build/
  - cd ../build/
  - cmake "$SRCDIR" -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build .
  - ctest
