dist: trusty
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - gcc-6
      - g++-6
      - clang-5
      - cmake
      - libboost-dev
      - ninja
script:
  - cmake -GNinja
  - ninja
  - ninja test
